### ISSUE TITLE
Could you take your writeup.ai and put it in separate projects?

### ISSUE THREAD

**Issue by tianshuo** [jeffshek/open#125]
Putting all projects in one GitHub project isn't a good idea.

**Comment by jeffshek** [comment]
hi @tianshuo sorry! you're right, it's definitely an anti-pattern for scaling code across teams, but this current setup lets me handle multiple projects concurrently while still having great tooling (sentry, circleci, etc). at the moment, most of the code here is based on writeup, so it should be a bit straight forward to remove any apps that don't belong to it.

best,
jeff
