### ISSUE TITLE
What Am I missing?

### ISSUE THREAD

**Issue by viveklse** [jeffshek/open#144]
Hi,

I am a student at Lone Star College with a keen interest in LM. Yesterday I found your app - writeup.ai on producthunt and how flawlessly it works is truly impressive. Then I found you have made the source code public but here "https://github.com/jeffshek/writeup-frontend" it reads - Open Sourced Backend (Mostly).

Now, I am confused about what I will be missing if I try to replicate your app on my system. I don't intent to run 1.5B or your models but my custom model (334M trained on 100MB of NCBI dataset).

Also, I plan on running it on my PC. I have had success running both 334 and 774 models on my system with core i7 8th gen, 1060 6GB (Cuda supported) and 32gigs ram so I am confident my system should be able to handle this app too.

Any help would be greatly appreciated.

Regards.

**Comment by designgrande** [comment]
Sorry dude, he ain't gonna help you.

**Comment by jeffshek** [comment]
@designgrande haha, i'lll try to do my best

@viveklse - this repo is the backend, writeup-frontend is the front-end. the last component you will need to do is setup the services architecture to spit back the dataset. 

the service has to easily fetch your responses back quickly.

https://senrigan.io/blog/how-writeupai-runs-behind-the-scenes/ - i've written a bit detailed about how it did it here. 

i do think my entire architecture is a over-optimized for speed, so it can be harder to grok. (apologies)
